s3_endpoint = "http://[::1]:3900"
k2v_endpoint = "http://[::1]:3904"
aws_region = "garage"

[imap]
bind_addr = "[::1]:4567"

[login_static.users.quentin]
password = "$argon2id$v=19$m=4096,t=3,p=1$jR52Nq76f8yO0UXdhK+FiQ$KeIzDI4PJ/2bX+expyyaRkMZus0/1FsgTXtnvPUjwyw"
aws_access_key_id = "GK68198c3b4148f61dcd625b7e"
aws_secret_access_key = "1d4bd3853a4f7810b97cbb2f8eb52c7603eb93c202fe98ca40f4e3f6b7e70fa0"
user_secret = "poupou"
bucket = "quentin-mailrage"
