name: Continuous integration

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_check:
    name: Rust code checks
    runs-on: rust-latest
    steps:
      - uses: actions/checkout@v7
      - name: Get Rust toolchain version
        id: get_rust_toolchain_version
        run: |
          RUST_TOOLCHAIN=$(grep -Po 'channel\s*=\s*"\K[^"]+' rust-toolchain.toml)
          echo "rust_toolchain=$RUST_TOOLCHAIN" >> $GITHUB_OUTPUT
      - uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.get_rust_toolchain_version.outputs.rust_toolchain }}
          components: rustfmt
      - name: "Cargo formatting"
        if: $${{ always() }}
        run: cargo fmt --all --check
