[package]
name = "smtp-server-types"
version = "0.5.1"
authors = [
  # Léo authored this crate as part of Kannader, a SMTP server project.
  # We forked his code to vendor it in Aerogramme.
  # Find the original project at: https://github.com/Ekleog/kannader
  "Léo Gaspard <leo@gaspard.io>"
]
license = "MIT OR Apache-2.0"
categories = ["email", "network-programming"]
keywords = ["smtp", "server", "asynchronous", "email"]
description = "Types required for configuring the smtp-server crate"
edition = "2018"

[dependencies]
# internal 
smtp-message.workspace = true

# external
serde.workspace = true

